name: pyright Checks
on:
  workflow_call:


jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture:  x64

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r server-requirements.txt

      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.311 # Optional (change me!)
          pylance-version: latest-release

        continue-on-error: false
